### ISSUE TITLE
Add custom icon for a new image alignment option?

### ISSUE THREAD

**Issue by carlo-fontanos** [ckeditor/ckeditor5-build-balloon#28]
Hi, 

I am currently attempting to enable a new image alignment option for my balloon editor, but I got stuck at adding my own icon. I tried the following: 

```
BalloonEditor.create( document.querySelector( '#editor' ), {
	image: {
		toolbar: [
			'imageTextAlternative', '|',
			'imageStyle:full', 			
			'imageStyle:alignLeft', 
			'imageStyle:alignRight', 
			'imageStyle:contact' 
		],
		styles: [
			'full',
			'alignLeft',
			'alignRight',
			{ name: 'contact', icon: 'https://icons-for-free.com/iconfiles/png/512/svg+employee+general+human+human+list+list+member+icon-1320185155662043477.png', title: 'My contact style', className: 'my-contact-side-image' }
		]
	}
} );
```

But it doesn't work, and I'm getting the following error: 

`TypeError: Cannot read property 'getAttribute' of null`

Any solution please?

**Comment by ma2ciek** [comment]
Hi @carlo-fontanos,

I'm not sure if the URL to the icon is supported. cc @oleq.

For sure downloaded icons can replace the existing ones during the compilation as you can read here: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#how-to-customize-the-ckeditor-5-icons. But I'm not sure if it's possible via the editor configuration.

**Comment by oleq** [comment]
As stated in the [documentation](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_image-ImageConfig.html#member-styles), you can specify custom icons for image alignment styles:

```js
import customIcon from 'custom-icon.svg';

// ...

const imageConfig = {
    styles: [
        // This will only customize the icon of the "full" style.
        // Note: 'right' is one of default icons provided by the feature.
        { name: 'full', icon: 'right' },

        // This will customize the icon, title and CSS class of the default "side" style.
        { name: 'side', icon: customIcon, title: 'My side style', className: 'custom-side-image' }
    ]
};
```

The thing is icons must be SVG because this is the only icon format supported by the UI of CKEditor 5. Knowing that, you're gonna need to 
* [build the editor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source) to import the icon like in the previous example (we're using [`raw-loader`](https://github.com/webpack-contrib/raw-loader) for that)
* specify it inline as string, for instance `my-style` below will be represented by a red rectangle
    ```js
    styles: [
        'alignLeft',
        'alignCenter',
        'alignRight',
        {
            name: 'my-style',
            icon: '<svg width="20" height="20" xmlns="http://www.w3.org/2000/svg"><path d="M3 3h14v13H3z" fill="#ff0000" /></svg>',
            title: 'My image style',
            className: 'my-image'
        }
    ],
    toolbar: [ 'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight', 'imageStyle:my-style' ]
    ```

I hope this will help you out.

**Comment by carlo-fontanos** [comment]
Thanks @oleq, I am using the CDN version to initialize CKEditor, and your recommendation to use SVG is the one that have worked for me.
